language: node_js
node_js:
  - '10'
install:
  - yarn install
before_deploy:
  - yarn run build-deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
